version: "3"

services:

  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - ./db:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: tindev
  
  mongotest:
    image: mongo
    container_name: mongodbtest
    command: mongod --port 27018
    volumes:
      - ./dbtest:/data/db
    restart: always
    ports:
      - 27018:27018
    environment:
      MONGO_INITDB_DATABASE: tindev

  app:
    build: .
    container_name: nodejs
    command: npm start
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - mongo
  
  apptest:
    build: .
    environment:
      - ENVIRONMENT=test
    container_name: nodejstest
    command: npm start
    volumes:
      - ./:/app
    ports:
      - 7000:7000
    depends_on:
      - mongotest
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodbserver
      ME_CONFIG_MONGODB_SERVER: mongotest
      ME_CONFIG_MONGODB_PORT: 27018
    depends_on:
      - mongo
      - mongotest