version: "3"

services:
  app:
    build: .
    container_name: nodejs
    command: npm start
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - ./db:/data/db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: tindev
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodbserver
      ME_CONFIG_MONGODB_SERVER: mongo

